shelly:
  auth:
    username: ''
    password: ''
  devices:
    discovery-interval: PT5M
    hosts: [ ]

  gen2auth:
    username: 'admin' # not changeable at the moment
    password: ${shelly.auth.password}
  gen2devices:
    discovery-interval: ${shelly.devices.discovery-interval}
    hosts: [ ]

  http-params:
    connect-timeout: PT5S
    request-timeout: PT5S
    validation-period: PT0.5S
    time-to-live: PT5S
    max-connections-total: 200
    max-connections-per-route: 10

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: prometheus
      exposure:
        include:
          - prometheus

  metrics:
    use-global-registry: false
  prometheus:
    metrics:
      export:
        step: PT1M

spring:
  profiles:
    include: local

logging:
  level:
    click.dobel.shelly.exporter.metrics.prometheus: DEBUG
