name: JDK compatibility tests
on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_NAME: ghcr.io/${{ github.repository }}

jobs:
  test:
    name: "Build ${{ matrix.test-image }}/${{ matrix.platform }}"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test-image:
          - eclipse-temurin:11
          - eclipse-temurin:11-alpine
          - eclipse-temurin:17
          - eclipse-temurin:17-alpine
          - amazoncorretto:11
          - amazoncorretto:17
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/arm/v7
      fail-fast: false
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: "Build the Docker test image"
        run: |
          docker build \
            --build-arg TEST_IMAGE=${{ matrix.test-image }} \
            --platform ${{ matrix.platform }} \
            --target test \
            .
