---
name: Release Please
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-22.04
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.2.10
        id: release
        with:
          package-name: shelly-exporter
          release-type: simple
          extra-files: |
            README.md
            pom.xml

  trigger-tagged-build:
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ${{ github.repository }}/.github/workflows/docker-container.yaml@v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
